version: '2'
services:
    db_e_ramal:
        container_name: db_e_ramal
        image: sameersbn/mysql
        volumes:
            - ./infra/data:/var/lib/mysql
        environment:
            - DB_NAME=demoDb
            - DB_USER=demoUser
            - DB_PASS=demoPass
        ports:
            - "33060:3306"
    php_e_ramal:
        container_name: php_e_ramal
        image: bitnami/php-fpm:latest
        ports:
          - '9000:9000'
        volumes:
            - ./backend:/var/www/e_ramal
    web_e_ramal:
        container_name: web_e_ramal
        image: nginx:latest
        links:
            - db_e_ramal
            - php_e_ramal
        ports:
            - "8080:80"
        volumes:
            - ./backend:/var/www/e_ramal
            - ./devops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - db_e_ramal
